#!/bin/sh

OAUTH_CONSUMER_KEY=컨슈머 키 입력
OAUTH_CONSUMER_SECRET=컨슈머 시크릿 키 입력
KEY_STORAGE_PATH=letsencrypt의 privekey.pem과 cert.pem 키가 존재하는 디렉토리 경로 입력
LOADBALANCER_INSTANCE_NUMBER=변경하고자하는 로드밸런서의 숫자 아이디

OAUTH_CONSUMER_KEY=$OAUTH_CONSUMER_KEY \
OAUTH_CONSUMER_SECRET=$OAUTH_CONSUMER_SECRET \
KEY_STORAGE_PATH=$KEY_STORAGE_PATH \
LOADBALANCER_INSTANCE_NUMBER=$LOADBALANCER_INSTANCE_NUMBER \
node index.js
